projects:
  - travis-ci/travis-ci
  - rails/rails
  - sinatra/sinatra
  - bundler/bundler
monit:
- :host: localhost
  :port: 2812
  :auth: true
  :username: admin
  :password: admin

- :host: localhost
  :port: 2812
  :auth: true
  :username: admin
  :password: admin
